name: 'Setup Node.js and Dependencies'
description: 'Sets up Node.js with caching and installs dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22.x'
  cache-dependency-path:
    description: 'Path to cache dependencies'
    required: false
    default: 'package-lock.json'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Display Node.js and npm versions
      shell: bash
      run: |
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"