name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to build for"
        required: false
        default: "development"
        type: string
    outputs:
      build-success:
        description: "Whether the build was successful"
        value: ${{ jobs.build.outputs.success }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.build.outcome == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps

      - name: Build project
        id: build
        run: npm run build
        env:
          NODE_ENV: ${{ inputs.environment }}

      - name: Check TypeScript compilation
        run: npx tsc --noEmit
