name: Build Only

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: "20.x"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      node-version: ${{ inputs.node-version || '20.x' }}
      cache-artifacts: true
      environment: "production"
