name: Build Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: "20.x"
        type: string
      cache-artifacts:
        description: "Whether to cache build artifacts"
        required: false
        default: true
        type: boolean
      environment:
        description: "Environment to build for"
        required: false
        default: "production"
        type: string
    outputs:
      build-success:
        description: "Whether the build was successful"
        value: ${{ jobs.build.outputs.success }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.build.outcome == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps
        with:
          node-version: ${{ inputs.node-version }}

      - name: Build project
        id: build
        run: npm run build
        env:
          NODE_ENV: ${{ inputs.environment }}

      - name: Check TypeScript compilation
        run: npx tsc --noEmit

      - name: Cache build artifacts
        if: ${{ inputs.cache-artifacts }}
        uses: actions/cache@v3
        with:
          path: |
            build/
            .strapi/
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-
