name: Manual CI Pipeline

on:
  workflow_dispatch:
    inputs:
      node-versions:
        description: "Node versions to test (comma separated)"
        required: false
        default: "18.x,20.x,22.x"
      run-security:
        description: "Run security checks"
        required: false
        default: true
        type: boolean

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      node-version: "20.x"
      cache-artifacts: true
      environment: "production"

  quality:
    if: ${{ inputs.run-security }}
    uses: ./.github/workflows/quality.yml
    needs: build
    with:
      node-version: "20.x"

  multi-node-test:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Simplified for now
    uses: ./.github/workflows/build.yml
    with:
      node-version: ${{ matrix.node-version }}
      cache-artifacts: false
      environment: "production"
