name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "production"
        type: choice
        options:
          - production
          - staging

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      node-version: "20.x"
      cache-artifacts: true
      environment: ${{ inputs.environment || 'production' }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-success == 'true' }}
    environment: ${{ inputs.environment || 'production' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-deps
        with:
          node-version: "20.x"

      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            build/
            .strapi/
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}

      - name: Deploy notification
        run: |
          echo "🚀 Deploying to ${{ inputs.environment || 'production' }}"
          echo "✅ Build completed successfully"
          echo "📦 Artifacts ready for deployment"

      # Add your actual deployment steps here
      # Examples:
      # - Deploy to Render
      # - Deploy to Vercel
      # - Deploy to AWS
      # - Deploy to Heroku
      # etc.
